version: '3.8'

services:
  portfolio:
    image: shhmon/portfolio:latest
    container_name: portfolio
    ports:
      - "5001:5000"
    env_file:
      - .env

  grippendor:
    image: shhmon/grippendor:latest
    container_name: grippendor
    ports:
      - "5002:5000"
    env_file:
      - .env
    depends_on:
      - grippendor-backend
      - grippendor-database

  grippendor-backend:
    image: shhmon/grippendor-backend:latest
    container_name: grippendor-backend
    env_file:
      - .env
    ports:
      - "5003:5003"
    depends_on:
      grippendor-database:
        condition: service_healthy

  grippendor-database:
    image: postgres:13
    container_name: grippendor-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${GRIPPENDOR_DB_PASSWORD}
      - POSTGRES_DB=${GRIPPENDOR_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - bot_db_volume:/var/lib/postgresql/data
      - /home/ec2-user/portfolio/grippendor-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${GRIPPENDOR_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  weather-app:
    image: shhmon/guruweather:latest
    container_name: guruweather
    environment:
      - REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}
    env_file:
      - .env
    ports:
      - "5004:5000"

  noto-frontend:
    image: shhmon/noto-frontend:latest
    container_name: noto
    ports:
      - "5005:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - noto-backend
      - noto-database

  noto-backend:
    image: shhmon/noto-backend:latest
    container_name: noto-backend
    env_file:
      - .env
    ports:
      - "5006:5006"
    depends_on:
      noto-db:
        condition: service_healthy

  noto-database:
    image: postgres:13
    container_name: noto-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${NOTO_DB_PASSWORD}
      - POSTGRES_DB=${NOTO_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - noto_db_volume:/var/lib/postgresql/data
      - /home/ec2-user/portfolio/Noto-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${NOTO_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  bot_db_volume:
  noto_db_volume:
